export const PAKISTAN_CITIES = [
  "Abbottabad",
  "Bahawalpur",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Gilgit",
  "Gujranwala",
  "Gujrat",
  "Hyderabad",
  "Islamabad",
  "Jhelum",
  "Karachi",
  "Kasur",
  "Lahore",
  "Mardan",
  "Mingora",
  "Mirpur",
  "Multan",
  "Murree",
  "Muzaffarabad",
  "Nawabshah",
  "Nowshera",
  "Peshawar",
  "Quetta",
  "Rawalpindi",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Sialkot",
  "Sukkur",
  "Swabi"
];